//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRABAJADOR
    {
        public int id_tra { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public decimal sueldo_b { get; set; }
        public string categoria { get; set; }
    }
}
